apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: books
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abmounir/devsecops-gitops-pipeline.git
    targetRevision: v3.0.0
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: books